namespace LibCpp2IL.Elf;

// ReSharper disable InconsistentNaming
public enum ElfDynamicType : long
{
    DT_NULL = 0,
    DT_NEEDED = 1,
    DT_PLTRELSZ = 2,
    DT_PLTGOT = 0x3,
    DT_HASH = 0x4,
    DT_STRTAB = 0x5,
    DT_SYMTAB = 0x6,
    DT_RELA = 0x7,
    DT_RELASZ = 0x8,
    DT_RELAENT = 0x9,
    DT_STRSZ = 0xa,
    DT_SYMENT = 0xb,
    DT_INIT = 0xC,
    DT_FINI = 0xD,
    DT_REL = 0x11,
    DT_RELSZ = 0x12,
    DT_RELENT = 0x13,
    DT_PLTREL = 0x14,
    DT_DEBUG = 0x15,
    DT_TEXTREL = 0x16,
    DT_JMPREL = 0x17,
    DT_BIND_NOW = 0x18,
    DT_INIT_ARRAY = 0x19,
    DT_FINI_ARRAY = 0x1A,
    DT_INIT_ARRAYSZ = 0x1B,
    DT_FINI_ARRAYSZ = 0x1C,
    DT_RUNPATH = 0x1D,
    DT_FLAGS = 0x1E,
    DT_PREINIT_ARRAY = 0x20,
    DT_PREINIT_ARRAYSZ = 0x21,
    DT_MAXPOSTAGS = 0x22,
    DT_RELRSZ = 0x23,
    DT_RELR = 0x24,
    DT_RELRENT = 0x25,
    DT_LOOS = 0x6000000D,
    DT_ANDROID_REL = DT_LOOS + 2,
    DT_ANDROID_RELSZ = DT_LOOS + 3,
    DT_ANDROID_RELA = DT_LOOS + 4,
    DT_ANDROID_RELASZ = DT_LOOS + 5,
    DT_ANDROID_RELR = 0x6fffe000,
    DT_ANDROID_RELRSZ = 0x6fffe001,
    DT_ANDROID_RELRENT = 0x6fffe003,
    DT_ANDROID_RELRCOUNT = 0x6fffe005,
}
