<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.0.10"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.0.10"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.10"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cpp2IL.Core\Cpp2IL.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
